# EXPORTS
export ZSH=$HOME/.oh-my-zsh
export TERM="xterm-256color"
export EDITOR='vi'
export PATH
# rclone
export RCLONE_PASSWORD_COMMAND="pass rc"

# ENV VARIABLES
DEFAULT_USER=rchint1
ZSH_THEME="robbyrussell"
KREW_PATH=${KREW_ROOT:-$HOME/.krew}/bin
DISABLE_MAGIC_FUNCTIONS="true"
# OS specific variables
if [[ "${OSTYPE}" == darwin* ]]; then
	SLEGE_PATH=~/.slege/bin
	TEX_PATH=/usr/local/texlive/2021/bin/universal-darwin
	GO_PATH=~/go/bin
	PROTOC_PATH=~/protoc-3.7.0-osx-x86_64/bin
	RVM_PATH=$HOME/.rvm/bin
	PATH=$SLEGE_PATH:$GOPATH:$TEX_PATH:$RVM_PATH:$PROTOC_PATH:$KREW_PATH:/usr/local/bin:$PATH
fi

# automatically update omz 
zstyle ':omz:update' mode auto
# select latest file in that directory
zstyle ':completion:*' file-sort date
# keychain settings
zstyle :omz:plugins:keychain agents gpg,ssh
zstyle :omz:plugins:keychain identities id_rsa 80DE15A80341233088142CFE134B443F329ED543

# PLUGIN MANAGER
# zplug
# install zplug, plugin manager for zsh, https://github.com/zplug/zplug
# curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
# zplug configruation
if [[ ! -d "${ZPLUG_HOME}" ]]; then
  if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    # If we can't get zplug, it'll be a very sobering shell experience. To at
    # least complete the sourcing of this file, we'll define an always-false
    # returning zplug function.
    if [[ $? != 0 ]]; then
      function zplug() {
        return 1
      }
    fi
  fi
  export ZPLUG_HOME=~/.zplug
fi
if [[ -d "${ZPLUG_HOME}" ]]; then
  source "${ZPLUG_HOME}/init.zsh"
fi

zplug 'plugins/git', from:oh-my-zsh, if:'which git'
zplug 'plugins/copybuffer', from:oh-my-zsh
zplug 'plugins/docker', from:oh-my-zsh, if:'which docker'
zplug 'plugins/fzf', from:oh-my-zsh, if:'which fzf'
zplug 'plugins/kubectl', from:oh-my-zsh, if:'which kubectl'
zplug 'plugins/kube-ps1', from:oh-my-zsh, if:'which kubectl'
zplug 'plugins/gpg-agent', from:oh-my-zsh, if:'which gpg'
zplug 'plugins/keychain', from:oh-my-zsh, if:'which keychain'
zplug 'plugins/gcloud', from:oh-my-zsh, if:'which gcloud'
zplug 'plugins/pass', from:oh-my-zsh, if:'which pass'
zplug 'plugins/nvm', from:oh-my-zsh, if:'which nvm'
zplug 'plugins/tmux', from:oh-my-zsh, if:'which tmux'
zplug "agkozak/zsh-z"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "Aloxaf/fzf-tab", if:'which fzf', defer:2
if ! zplug check; then
    zplug install
fi
# source plugins and add commands to the PATH
zplug load

# SOURCE oh-my-zsh after plugins 
source $ZSH/oh-my-zsh.sh
source ~/.profile

if command -v kube_ps1 > /dev/null ; then
    PROMPT='$(kube_ps1)'$PROMPT
fi
# KEY BINDINGS
bindkey '^ ' autosuggest-accept
