# EXPORTS
export ZSH=$HOME/.oh-my-zsh
export TERM="xterm-256color"
export EDITOR='vi'
export PATH
# rclone
export RCLONE_PASSWORD_COMMAND="pass rc"

# PLUGIN MANAGER
# zplug
source ~/.zplug/init.zsh
zplug "agkozak/zsh-z"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
if ! zplug check; then
    zplug install
fi
# source plugins and add commands to the PATH
zplug load

# ENV VARIABLES
DEFAULT_USER=rchint1
ZSH_THEME="robbyrussell"
KREW_PATH=${KREW_ROOT:-$HOME/.krew}/bin
# OS specific variables
if [[ "${OSTYPE}" == darwin* ]]; then
	SLEGE_PATH=~/.slege/bin
	TEX_PATH=/usr/local/texlive/2021/bin/universal-darwin
	GO_PATH=~/go/bin
	PROTOC_PATH=~/protoc-3.7.0-osx-x86_64/bin
	RVM_PATH=$HOME/.rvm/bin
	PATH=$SLEGE_PATH:$GOPATH:$TEX_PATH:$RVM_PATH:$PROTOC_PATH:$KREW_PATH:/usr/local/bin:$PATH
fi


# automatically update omz 
zstyle ':omz:update' mode auto
# forces zsh to realize new commands
zstyle ':completion:*' completer _oldlist _expand _complete _match _ignored _approximate
# select latest file in that directory
zstyle ':completion:*' file-sort date
# fix for slow paste
zstyle ':bracketed-paste-magic' active-widgets '.self-*'
# keychain settings
zstyle :omz:plugins:keychain agents gpg,ssh
zstyle :omz:plugins:keychain identities id_rsa 80DE15A80341233088142CFE134B443F329ED543

# Plugins
# Which plugins would you like to load? 
# (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(
	copybuffer
	copyfile
	docker
	dotenv
	emacs
	fasd 
	fzf
	keychain
	kubectl
	kube-ps1
	git 
	gpg-agent
	gcloud
	pass
	nvm
	tmux
)

# SOURCE oh-my-zsh after plugins 
source $ZSH/oh-my-zsh.sh
source ~/.profile

PROMPT='$(kube_ps1)'$PROMPT

# KEY BINDINGS
bindkey '^ ' autosuggest-accept
bindkey "^x^o" copybuffer
